# Generated by Django 4.2.11 on 2024-06-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_member_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/plot_photos/'),
        ),
    ]
